[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"] # this should give us memset, memcpy, and memcmp

[toolchain]
channel = "nightly"

[build]
target = "target.json"